name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-18.04  # Linux 环境，用于构建 .deb 包
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt and dependencies
        run: sudo apt install qtbase5-dev qtwebengine5-dev nsis

      - name: Build .deb package
        run: bash scripts/build.sh build

      - name: Create Release for .deb package
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/md-editor-*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.MD }}

  build-exe:
    runs-on: windows-latest  # Windows 环境，用于构建 .exe 包
    steps:
      - uses: actions/checkout@v4

      - name: Install ImageMagick (convert SVG to ICO)
        run: choco install imagemagick -y

      - name: Install Qt and dependencies
        run: |
          choco install qt5
          choco install nsis

      - name: Generate icon.ico for Windows resources
        run: magick src/resources/icon.svg src/resources/icon.ico
      
      - name: Set Qt5_DIR for CMake
        run: |
          echo "Qt5_DIR=C:/Program Files/Qt/5.15.2/msvc2019_64/lib/cmake/Qt5" >> $GITHUB_ENV

      - name: Build .exe package
        run: bash scripts/build.sh build

      - name: Create Release for .exe package
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/md-editor-*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MD }}
